#ifndef __CONF_WDSP_H
#define __CONF_WDSP_H

#include "config.h"

#define BLOCK_SIZE CONFIG_AUDIO_BLOCK_SIZE
#define SAMPLE_RATE CONFIG_AUDIO_SAMPLE_RATE
#define NUM_CHANNELS CONFIG_AUDIO_CHANNELS

#endif