# WhateverDSP library build file

include buildvars.mk

TARGET ?= $(LIB_NAME)

# C sources
C_SOURCES = \
src/wdsp.c

# ASM sources
ASM_SOURCES =

# C includes
C_INCLUDES = \
-I $(CONFIG_DIR)/ \
-I includes \
-I includes/arm \
-I includes/cmsis \
-I includes/stm

C_DEFS += -DLIB_BUILD

include boards/$(BOARD)/board.mk
include boards/$(BOARD)/build.mk
include cores/$(CORE)/core.mk
include cores/$(CORE)/build.mk

# Reset default goal so it doesn't get overriden by rules in the included files
.DEFAULT_GOAL :=

$(info building $(TARGET).a for board $(BOARD))

# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(sort $(C_SOURCES:.c=.o))))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(sort $(ASM_SOURCES:.s=.o))))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

.PHONY: all
all: config $(OBJECTS) $(TARGET).a($(OBJECTS))

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR):
	mkdir -p $@

$(CONFIG_DIR):
	mkdir -p $@

$(CONFIG_DIR)/config.%: boards/$(BOARD)/config.ini $(USER_CONFIG) | $(CONFIG_DIR)
	awk -f tools/mkconf.awk -v mode=$* $^ > $@


# Include autogenerated dependency information
-include $(wildcard $(BUILD_DIR)/*.d)

.PHONY: config
config: $(CONFIG_DIR)/config.h $(CONFIG_DIR)/config.mk

.PHONY: clean
clean:
	-rm -f $(OBJECTS) $(OBJECTS:%.o=%.d) $(OBJECTS:%.o=%.lst) $(TARGET).a $(CONFIG_DIR)/config.h $(CONFIG_DIR)/config.mk
	-rmdir $(CONFIG_DIR) $(BUILD_DIR)
