#ifndef __CONF_USB_CONFIG_H
#define __CONF_USB_CONFIG_H

#include "config.h"

#define USB_VID CONFIG_USB_VID
#define USB_PID CONFIG_USB_PID
#define USB_DEVICE_VER CONFIG_USB_DEVICE_VERSION

#define USB_MANUFACTURER_STR CONFIG_USB_VENDOR_NAME
#define USB_PRODUCT_STR CONFIG_USB_PRODUCT_NAME

#endif